### ISSUE TITLE
[0.5pt] Set up the project with Webpack and Jest- group task

### ISSUE THREAD

**Issue by SaveryIV** [SaveryIV/Javascript-Capstone-Project#18]
- Set up Gitflow
- Set up webpack
- Set up a JavaScript testing library (Jest)

**Comment by SaveryIV** [comment]
Now i push the config of Webpack and the Linters here: https://github.com/SaveryIV/Javascript-Capstone-Project @Uzair-Manzoor

**Comment by Uzair-Manzoor** [comment]
configured and set up Jest for testing purposes "[link to the pull request](https://github.com/SaveryIV/Javascript-Capstone-Project/pull/25)"

**Comment by Uzair-Manzoor** [comment]
added necessary dependencies for Babel and Jest and created a .babelrc configuration file in project's root directory [PR link](https://github.com/SaveryIV/Javascript-Capstone-Project/pull/27)
